import "./globals.css";
import Footer from "@/components/footer/Footer";
import HeaderWrapper from "@/components/header/HeaderWrapper";

export const metadata = {
  title: "Gecora Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Sticky Header */}
        <div className="sticky top-0 z-[999]">
          <HeaderWrapper />
        </div>

        {children}

        <div className="w-full bg-white mx-auto">
          <Footer />
        </div>
      </body>
    </html>
  );
}
