import { Roboto} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import Navbar from "@/components/header/navBar";
import Footer from "@/components/footer/Footer";
import TopFooter from "@/components/footer/topFooter";
import TopNav from "@/components/header/topNav";
import TrendingPlayers from "@/components/home/TrendingPlayers";
import TeamFeatures from "@/components/home/TeamFeatures";
// import NavbarInfoSlider from "@/components/header/navbarInfoSlider";
import CardCarousel from "@/components/header/cardCarousel";
    import KeySeries from "@/components/home/KeySeries";
    import Writter from "@/components/home/Writter";
    import Edditor from "@/components/home/Edditor";

 

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased bg-white dark:bg-gray-900 text-black dark:text-white transition-colors duration-300`}
      >
        <ThemeProvider>
          <TopNav/>
          <CardCarousel/>
           {/* <NavbarInfoSlider/>  */}
          <Navbar/>
          {/* <SecondaryNav/>
           <TrendingPlayers/>
          <Edditor/>
          <TeamFeatures/>
          <Writter/>
          <KeySeries/> */}

          {children}
          <TopFooter/>
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
